name: ToggleOpPlus
main: com.bennyman123abc.ToggleOP
version: 1.2DEVBuild1
commands:
    toggleop:
        description: Toggles Op For Owners and Co-Owners or a Player of Their Choice
        usage: